### PR TITLE
#6 Changing Activity and Discord.js Start 

### LINKED ISSUE #6: Changing Activity
I saw on Discord, that you want to change your bot to Discord.js. I'm Discord.js Dev and would add changing activities with a basic index so that the others can start adding stuff up to that.

### PR DESCRIPTION
**Pull request by YockerFX**
This pull request includes changes to the environment variables and the main application file to integrate with Discord's API. The most important changes include updating the environment variable name and adding new functionality to the `index.js` file to manage a Discord bot.

Environment variable update:

* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL1-R1): Changed `TOKEN` to `BOT_TOKEN` to clarify its purpose for the Discord bot.

Discord bot integration:

* [`index.js`](diffhunk://#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R1-R25): Added the `dotenv` package to load environment variables, initialized a Discord client with specific intents, created a function to update the bot's status, and set up a timer to change the status every 10 seconds. Also added an event listener to log when the bot is ready and to start the status update process.

### CODE REVIEW

**Comment by halcyon-past** [comment]
hey @YockerFX The main functionality of the bot itself is missing with this
not just the index file this needs migration of all the previous functionalities as well

**Comment by YockerFX** [comment]
I wanted to leave that open so that other also can get some prs for the Hacktoberfest event, but if you want I can add that also.

**Comment by ConnectAlumni** [comment]
@YockerFX can u ignore node_modules please I can't even pull

**Comment by MannuVilasara** [comment]
@YockerFX Can you gitignore node_modules (who pushes node modules to codebase?)

**Comment by YockerFX** [comment]
Didn't noticed that I also had them in

**Comment by halcyon-past** [comment]
@YockerFX I would suggest if you are just leaving the template then make a readme explaining what needs to be done next for the next user to contribute because without that this will just be a blank discord bot without context since previous codes will be overridden

**Comment by YockerFX** [comment]
Done

**Pull request merged**
